"""
Financial profile utilities for firm-aware agent calibration.

The model can run without any external workbook.  When financial data is
present it is loaded from (in priority order):

  1. all_peer_financials.xlsx  — comprehensive workbook covering all companies
     in AGENT_FINANCIAL_PEERS, generated by collect_all_agent_financials.py.
  2. listed_company_tiers_financials.xlsx  — seed workbook covering companies
     extracted from the supply-chain HTML dashboard.

Both workbooks must contain a "financials_by_year" sheet with at least the
columns: company_name, fiscal_year, and the financial-metric columns below.

Five-year company financials are converted to conservative multipliers:

  recovery_multiplier   — how quickly capacity recovers after a shock
  inventory_multiplier  — how much buffer stock the agent can sustain
  growth_multiplier     — capacity growth relative to baseline growth rate
  shock_absorption      — fraction of an incoming shock cushioned by
                          balance-sheet strength and cash generation

Multipliers are deliberately bounded so financial data nudges behaviour
rather than overwhelming the engineering / supply-chain calibration.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Iterable

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FINANCIAL_WORKBOOK = ROOT / "listed_company_tiers_financials.xlsx"
ALL_PEER_WORKBOOK = ROOT / "all_peer_financials.xlsx"


@dataclass(frozen=True)
class FinancialProfile:
    company_names: tuple[str, ...] = ()
    revenue_latest: float = 0.0
    revenue_cagr: float = 0.0
    operating_margin: float = 0.0
    free_cash_flow_margin: float = 0.0
    capex_intensity: float = 0.0
    debt_to_assets: float = 0.0
    recovery_multiplier: float = 1.0
    inventory_multiplier: float = 1.0
    growth_multiplier: float = 1.0
    shock_absorption: float = 0.0


DEFAULT_PROFILE = FinancialProfile()


# ── Ticker map ────────────────────────────────────────────────────────────────
# Maps company_name (as used in AGENT_FINANCIAL_PEERS) to Yahoo Finance symbol.
# Used by collect_all_agent_financials.py to refresh financial data.

AGENT_PEER_TICKERS: dict[str, str] = {
    # ── Tier 2: Cell manufacturers ──────────────────────────────────────────
    "CATL":                 "300750.SZ",
    "BYD":                  "002594.SZ",
    "LG Energy Solution":   "373220.KS",
    "Panasonic":            "6752.T",
    "Samsung SDI":          "006400.KS",
    "SK On":                "096770.KS",   # parent SK Innovation / SK IE Technology
    "CALB":                 "3931.HK",
    "EVE Energy":           "300014.SZ",
    "Gotion High-Tech":     "002074.SZ",
    "Farasis Energy":       "688567.SS",
    "Sunwoda Electronic":   "300207.SZ",

    # ── Tier 1: Lithium suppliers ────────────────────────────────────────────
    "Albemarle":            "ALB",
    "SQM":                  "SQM",
    "Ganfeng Lithium":      "002460.SZ",
    "Tianqi Lithium":       "002466.SZ",
    "Pilbara Minerals":     "PLS.AX",
    "Mineral Resources":    "MIN.AX",

    # ── Tier 1: Cobalt / nickel / copper suppliers ───────────────────────────
    "Glencore":             "GLEN.L",
    "CMOC Group":           "3993.HK",

    # ── Tier 1: Rare-earth suppliers ─────────────────────────────────────────
    "MP Materials":         "MP",
    "Lynas Rare Earths":    "LYC.AX",
    "China Northern Rare Earth": "600111.SS",

    # ── Tier 1: Cathode / anode material processors ──────────────────────────
    "Umicore":              "UMI.BR",
    "POSCO Holdings":       "005490.KS",
    "Syrah Resources":      "SYR.AX",

    # ── Tier 2: SiC / power semiconductors ───────────────────────────────────
    "Wolfspeed":            "WOLF",
    "Coherent":             "COHR",
    "STMicroelectronics":   "STM",
    "Infineon Technologies":"IFX.DE",
    "ON Semiconductor":     "ON",
    "Rohm":                 "6963.T",
    "Mitsubishi Electric":  "6503.T",
    "Fuji Electric":        "6504.T",

    # ── Tier 3: Inverter / powertrain subsystem ───────────────────────────────
    "BorgWarner":           "BWA",

    # ── Tier 3: Motor / drivetrain subsystem ─────────────────────────────────
    "Nidec":                "6594.T",
    "Denso":                "6902.T",
    "Schaeffler":           "SHA0.DE",
    "Magna International":  "MGA",

    # ── Tier 3: Harness / wiring subsystem ───────────────────────────────────
    "Aptiv":                "APTV",
    "Sumitomo Electric":    "5802.T",
    "TE Connectivity":      "TEL",

    # ── Tier 4: OEM — China ──────────────────────────────────────────────────
    "SAIC":                 "600104.SS",
    "Geely":                "0175.HK",
    "NIO":                  "NIO",
    "Li Auto":              "LI",
    "Xpeng":                "XPEV",
    "Leapmotor":            "9863.HK",

    # ── Tier 4: OEM — USA ────────────────────────────────────────────────────
    "Tesla":                "TSLA",
    "General Motors":       "GM",
    "Ford Motor":           "F",
    "Rivian":               "RIVN",
    "Lucid Group":          "LCID",

    # ── Tier 4: OEM — Europe ─────────────────────────────────────────────────
    "Volkswagen":           "VOW3.DE",
    "BMW":                  "BMW.DE",
    "Mercedes-Benz Group":  "MBG.DE",
    "Stellantis":           "STLA",

    # ── Tier 4: OEM — Korea / Japan ──────────────────────────────────────────
    "Hyundai Motor":        "005380.KS",
    "Kia":                  "000270.KS",
    "Toyota Motor":         "7203.T",
    "Honda Motor":          "7267.T",
    "Nissan Motor":         "7201.T",
}


# ── Agent → peer company mapping ─────────────────────────────────────────────
# Each agent_id maps to the listed companies that best represent its financial
# characteristics.  When multiple companies are listed, profiles are
# revenue-weighted.

AGENT_FINANCIAL_PEERS: dict[str, tuple[str, ...]] = {
    # ── Tier 2: Cell manufacturers ───────────────────────────────────────────
    "cell_catl":        ("CATL",),
    "cell_byd_cells":   ("BYD",),
    "cell_lg_es":       ("LG Energy Solution",),
    "cell_panasonic":   ("Panasonic",),
    "cell_samsung_sdi": ("Samsung SDI",),
    "cell_sk_on":       ("SK On",),
    "cell_calb":        ("CALB",),
    # AESC UK has no independent listing; use closest listed proxies by size/region
    "cell_aesc_uk":     ("Panasonic", "LG Energy Solution"),
    "cell_others_cells": (
        "EVE Energy", "Gotion High-Tech", "Farasis Energy", "Sunwoda Electronic",
    ),

    # ── Tier 3: Subsystem suppliers ──────────────────────────────────────────
    # Battery pack assembly — profile dominated by cell makers that also pack
    "t1_battery_pack": (
        "CATL", "BYD", "LG Energy Solution", "Panasonic", "Samsung SDI",
    ),
    # Inverter / power electronics — SiC and IGBT suppliers
    "t1_inverter": (
        "BorgWarner", "Infineon Technologies", "ON Semiconductor",
        "STMicroelectronics", "Wolfspeed", "Rohm", "Mitsubishi Electric",
    ),
    # Traction motor — PMSM and induction motor makers
    "t1_motor": (
        "Nidec", "BorgWarner", "Denso", "Mitsubishi Electric",
        "Schaeffler", "Magna International",
    ),
    # Wiring harness — labour-intensive JIT suppliers
    "t1_harness": ("Aptiv", "Sumitomo Electric", "TE Connectivity"),

    # ── Tier 4: OEM groups ────────────────────────────────────────────────────
    "oem_byd_oem":          ("BYD",),
    "oem_other_chinese_oem": (
        "SAIC", "Geely", "NIO", "Li Auto", "Xpeng", "Leapmotor",
    ),
    "oem_uk_oem":           ("BMW", "Stellantis", "Nissan Motor"),
    "oem_us_oem":           ("Tesla", "General Motors", "Ford Motor", "Rivian", "Lucid Group"),
    "oem_german_oem":       ("Volkswagen", "BMW", "Mercedes-Benz Group", "Stellantis"),
    "oem_korean_oem":       ("Hyundai Motor", "Kia"),
    "oem_japanese_oem":     ("Toyota Motor", "Honda Motor", "Nissan Motor"),

    # ── Tier 1: Mineral / material source agents ─────────────────────────────
    # Lithium
    "lithium_aus":      ("Pilbara Minerals", "Mineral Resources", "Albemarle"),
    "lithium_chl":      ("SQM", "Albemarle"),
    "lithium_chn":      ("Ganfeng Lithium", "Tianqi Lithium"),
    "lithium_other":    ("Albemarle", "SQM"),
    # Cobalt
    "cobalt_drc":       ("Glencore", "CMOC Group"),
    "cobalt_other":     ("Glencore",),
    # Graphite
    "graphite_chn":     ("Syrah Resources", "Ganfeng Lithium"),
    "graphite_other":   ("Syrah Resources",),
    # Rare earths
    "ree_chn":          ("China Northern Rare Earth",),
    "ree_other":        ("MP Materials", "Lynas Rare Earths"),
    # SiC wafer — by dominant supplier
    # Wolfspeed filed Chapter 11 in early 2025; Coherent is the closest listed
    # SiC peer when Wolfspeed financial data is unavailable.
    "sic_wolfspeed":    ("Wolfspeed", "Coherent"),
    "sic_coherent":     ("Coherent",),
    # China SiC: no pure-play listed proxy; use closest diversified peers
    "sic_china":        ("STMicroelectronics", "Infineon Technologies"),
    "sic_other":        ("STMicroelectronics", "Rohm", "Infineon Technologies"),
}


# ── Four-tier grouping of agent IDs ──────────────────────────────────────────
# Enables tier-level aggregate profile queries via profile_for_tier().

FOUR_TIER_AGENT_GROUPS: dict[str, list[str]] = {
    "Tier 1 - Raw & Processed Materials": [
        "lithium_aus", "lithium_chl", "lithium_chn", "lithium_other",
        "cobalt_drc", "cobalt_other",
        "graphite_chn", "graphite_other",
        "ree_chn", "ree_other",
        "sic_wolfspeed", "sic_coherent", "sic_china", "sic_other",
    ],
    "Tier 2 - Core Components": [
        "cell_catl", "cell_byd_cells", "cell_lg_es", "cell_panasonic",
        "cell_samsung_sdi", "cell_sk_on", "cell_calb", "cell_aesc_uk",
        "cell_others_cells",
    ],
    "Tier 3 - Subsystems / Tier-1 Integration": [
        "t1_battery_pack", "t1_inverter", "t1_motor", "t1_harness",
    ],
    "Tier 4 - OEM Assembly & Vehicle Integration": [
        "oem_byd_oem", "oem_other_chinese_oem", "oem_uk_oem",
        "oem_us_oem", "oem_german_oem", "oem_korean_oem", "oem_japanese_oem",
    ],
}


# ── Internal helpers ──────────────────────────────────────────────────────────

def _clip(value: float, low: float, high: float) -> float:
    return max(low, min(high, value))


def _safe_mean(series: pd.Series) -> float:
    series = pd.to_numeric(series, errors="coerce").dropna()
    return float(series.mean()) if not series.empty else 0.0


def _company_profile(rows: pd.DataFrame) -> FinancialProfile:
    rows = rows.sort_values("fiscal_year")
    company = str(rows["company_name"].iloc[0])
    latest  = rows.iloc[-1]
    first   = rows.iloc[0]
    years   = max(1, int(latest["fiscal_year"] - first["fiscal_year"]))

    latest_revenue = float(pd.to_numeric(latest.get("Revenue"), errors="coerce") or 0.0)
    first_revenue  = float(pd.to_numeric(first.get("Revenue"),  errors="coerce") or 0.0)
    if latest_revenue > 0 and first_revenue > 0 and years > 0:
        revenue_cagr = (latest_revenue / first_revenue) ** (1 / years) - 1
    else:
        revenue_cagr = 0.0

    revenue          = pd.to_numeric(rows.get("Revenue"),           errors="coerce").replace(0, pd.NA)
    operating_margin = _safe_mean(pd.to_numeric(rows.get("Operating income"),  errors="coerce") / revenue)
    fcf_margin       = _safe_mean(pd.to_numeric(rows.get("Free cash flow"),    errors="coerce") / revenue)
    capex_intensity  = _safe_mean(pd.to_numeric(rows.get("Capital expenditure"), errors="coerce").abs() / revenue)
    debt_to_assets   = _safe_mean(
        pd.to_numeric(rows.get("Total debt"),   errors="coerce")
        / pd.to_numeric(rows.get("Total assets"), errors="coerce").replace(0, pd.NA)
    )

    profitability_score = _clip(operating_margin / 0.12,   -0.5,  1.5)
    cash_score          = _clip(fcf_margin       / 0.08,   -0.5,  1.5)
    leverage_penalty    = _clip(debt_to_assets   / 0.45,    0.0,  1.5)
    capex_score         = _clip(capex_intensity  / 0.08,    0.0,  1.5)
    growth_score        = _clip(revenue_cagr     / 0.12,   -1.0,  2.0)

    resilience   = 1.0 + 0.18 * profitability_score + 0.16 * cash_score - 0.14 * leverage_penalty
    reinvestment = 1.0 + 0.12 * capex_score + 0.10 * growth_score - 0.08 * leverage_penalty

    return FinancialProfile(
        company_names=(company,),
        revenue_latest=latest_revenue,
        revenue_cagr=revenue_cagr,
        operating_margin=operating_margin,
        free_cash_flow_margin=fcf_margin,
        capex_intensity=capex_intensity,
        debt_to_assets=debt_to_assets,
        recovery_multiplier=_clip(resilience,   0.65, 1.45),
        inventory_multiplier=_clip(1.0 + 0.12 * cash_score - 0.10 * leverage_penalty, 0.75, 1.35),
        growth_multiplier=_clip(reinvestment,   0.60, 1.60),
        shock_absorption=_clip(
            0.06 * profitability_score + 0.06 * cash_score - 0.04 * leverage_penalty,
            0.0, 0.22,
        ),
    )


def _load_workbook(path: Path) -> dict[str, FinancialProfile]:
    """Load per-company profiles from a single workbook. Returns {} on failure."""
    if not path.exists():
        return {}
    try:
        financials = pd.read_excel(path, sheet_name="financials_by_year")
    except Exception:
        return {}
    if financials.empty or "company_name" not in financials.columns:
        return {}
    result: dict[str, FinancialProfile] = {}
    for company, rows in financials.groupby("company_name"):
        result[str(company)] = _company_profile(rows)
    return result


# ── Public API ────────────────────────────────────────────────────────────────

@lru_cache(maxsize=1)
def load_company_profiles() -> dict[str, FinancialProfile]:
    """
    Load and merge per-company profiles from all available financial workbooks.

    Priority: ALL_PEER_WORKBOOK (comprehensive) > DEFAULT_FINANCIAL_WORKBOOK (seed).
    A company found in the higher-priority workbook is not overwritten by the
    lower-priority one.
    """
    profiles: dict[str, FinancialProfile] = {}
    for wb_path in (ALL_PEER_WORKBOOK, DEFAULT_FINANCIAL_WORKBOOK):
        for company, profile in _load_workbook(wb_path).items():
            profiles.setdefault(company, profile)   # first hit wins
    return profiles


def combine_profiles(
    company_names: Iterable[str],
    workbook_path: str | None = None,   # kept for backward-compat; ignored
) -> FinancialProfile:
    """
    Return a revenue-weighted average profile for the given peer companies.
    Falls back to DEFAULT_PROFILE when no financial data is available.
    """
    all_profiles = load_company_profiles()
    selected = [all_profiles[n] for n in company_names if n in all_profiles]
    if not selected:
        return DEFAULT_PROFILE

    weights     = [p.revenue_latest if p.revenue_latest > 0 else 1.0 for p in selected]
    total_w     = sum(weights) or float(len(selected))

    def weighted(attr: str) -> float:
        return sum(getattr(p, attr) * w for p, w in zip(selected, weights)) / total_w

    names = tuple(n for p in selected for n in p.company_names)
    return FinancialProfile(
        company_names=names,
        revenue_latest=sum(p.revenue_latest for p in selected),
        revenue_cagr=weighted("revenue_cagr"),
        operating_margin=weighted("operating_margin"),
        free_cash_flow_margin=weighted("free_cash_flow_margin"),
        capex_intensity=weighted("capex_intensity"),
        debt_to_assets=weighted("debt_to_assets"),
        recovery_multiplier=weighted("recovery_multiplier"),
        inventory_multiplier=weighted("inventory_multiplier"),
        growth_multiplier=weighted("growth_multiplier"),
        shock_absorption=weighted("shock_absorption"),
    )


def profile_for_agent(agent_id: str) -> FinancialProfile:
    """Return the calibrated FinancialProfile for a model agent."""
    return combine_profiles(AGENT_FINANCIAL_PEERS.get(agent_id, ()))


def profile_for_tier(tier_label: str) -> FinancialProfile:
    """
    Return an aggregate FinancialProfile for all agents in a supply-chain tier.

    tier_label must be one of the keys in FOUR_TIER_AGENT_GROUPS.
    """
    agent_ids = FOUR_TIER_AGENT_GROUPS.get(tier_label, [])
    all_companies: list[str] = []
    for aid in agent_ids:
        all_companies.extend(AGENT_FINANCIAL_PEERS.get(aid, ()))
    return combine_profiles(all_companies)


def coverage_report() -> pd.DataFrame:
    """
    Return a DataFrame showing which agents have financial data and which don't.
    Useful for diagnosing missing data after running collect_all_agent_financials.py.
    """
    all_profiles = load_company_profiles()
    rows = []
    for agent_id, peers in AGENT_FINANCIAL_PEERS.items():
        matched   = [p for p in peers if p in all_profiles]
        unmatched = [p for p in peers if p not in all_profiles]
        profile   = combine_profiles(peers)
        rows.append({
            "agent_id":            agent_id,
            "peer_companies":      "; ".join(peers),
            "matched":             "; ".join(matched),
            "unmatched":           "; ".join(unmatched),
            "coverage_pct":        round(100 * len(matched) / max(len(peers), 1), 0),
            "recovery_multiplier": round(profile.recovery_multiplier, 3),
            "inventory_multiplier":round(profile.inventory_multiplier, 3),
            "growth_multiplier":   round(profile.growth_multiplier, 3),
            "shock_absorption":    round(profile.shock_absorption, 3),
        })
    return pd.DataFrame(rows)
